# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
v1=np.zeros(10)
v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [8]:
b=np.arange(10,49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [11]:
b.shape

(39,)

5. Print the type of the previous array in question 3

In [13]:
b.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [18]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [16]:
b.ndim

1

8. Create a boolean array with all the True values

In [21]:
bol_array= np.ones((1,10), dtype='bool')
bol_array

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

9. Create a two dimensional array




In [28]:
c= np.array([[1, 2], [3, 4]])
print(c)
c.shape

[[1 2]
 [3 4]]


(2, 2)

10. Create a three dimensional array



In [31]:
d=np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(d)
d.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [60]:
print(b)
b[::-1]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [66]:
n_vec= np.zeros((1,10))
n_vec[0,4]=1
n_vec

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

13. Create a 3x3 identity matrix

In [78]:
identity= np.ones((3,3), dtype='int32')
identity

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [84]:
print(identity.dtype)
identity_1 = identity.astype(np.float32)
print(identity_1.dtype)

int32
float32


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [88]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [91]:
arr3= arr1>arr2
arr3

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [100]:
arr= np.arange(0,10)
print(arr)
arr_odd= arr[arr%2==1]
arr_odd

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [99]:
arr[arr%2==1]= -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [106]:
arr= np.arange(10)
print(arr)
arr[5:9]=12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [143]:
d_2= np.ones((5,5))
print(d_2)
d_2[1:4, 1:4] = 0
print(d_2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [145]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [152]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [157]:
arr2d= np.arange(0,8).reshape(2,4)
print(arr2d)
arr2d[0]

[[0 1 2 3]
 [4 5 6 7]]


array([0, 1, 2, 3])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [158]:
arr2d= np.arange(0,8).reshape(2,4)
print(arr2d)
arr2d[1]

[[0 1 2 3]
 [4 5 6 7]]


array([4, 5, 6, 7])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [170]:
arr2d= np.arange(0,8).reshape(2,4)
print(arr2d)
arr2d[::, 2]

[[0 1 2 3]
 [4 5 6 7]]


array([2, 6])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [179]:
test= np.random.randint(10, size=(10,10))
print(test)
print(np.max(test))
print(np.min(test))

[[4 9 5 0 2 2 6 9 0 3]
 [7 2 4 4 1 8 6 9 1 1]
 [8 2 4 9 9 8 5 7 6 2]
 [6 4 5 0 5 5 0 6 0 9]
 [0 7 3 8 3 2 0 3 0 3]
 [7 7 3 9 0 8 7 3 9 2]
 [1 6 1 3 6 4 2 4 5 4]
 [2 2 0 2 6 6 8 3 9 4]
 [9 3 6 8 9 5 1 6 5 3]
 [6 5 6 3 8 0 8 8 3 1]]
9
0


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [188]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c= a==b
c = a[c]
c

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [189]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [193]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data


array([[ 0.34883107, -0.19070394,  0.76212718,  0.72225853],
       [ 1.45725232, -0.10584164, -0.54093665,  1.51111947],
       [-1.25297832,  0.15006068, -0.33005615,  0.10835525],
       [ 0.0275509 ,  0.04905408, -1.76570222, -0.12503942],
       [ 0.88211767,  1.70662477,  1.94602171,  0.70973602],
       [ 1.66102363, -1.10539977,  0.52446709,  0.096332  ],
       [-0.01422589, -1.8066789 , -2.33708717,  1.21274891]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [197]:
arr_2d= np.logspace(1,15,num=15, dtype='float32').reshape(5,3)
arr_2d

array([[1.e+01, 1.e+02, 1.e+03],
       [1.e+04, 1.e+05, 1.e+06],
       [1.e+07, 1.e+08, 1.e+09],
       [1.e+10, 1.e+11, 1.e+12],
       [1.e+13, 1.e+14, 1.e+15]], dtype=float32)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [198]:
arr_2d= np.logspace(1,16,num=16, dtype='float32').reshape(2,2,4)
arr_2d

array([[[1.e+01, 1.e+02, 1.e+03, 1.e+04],
        [1.e+05, 1.e+06, 1.e+07, 1.e+08]],

       [[1.e+09, 1.e+10, 1.e+11, 1.e+12],
        [1.e+13, 1.e+14, 1.e+15, 1.e+16]]], dtype=float32)

33. Swap axes of the array you created in Question 32

In [214]:
np.swapaxes(arr_2d,0,2)

array([[[1.e+01, 1.e+09],
        [1.e+05, 1.e+13]],

       [[1.e+02, 1.e+10],
        [1.e+06, 1.e+14]],

       [[1.e+03, 1.e+11],
        [1.e+07, 1.e+15]],

       [[1.e+04, 1.e+12],
        [1.e+08, 1.e+16]]], dtype=float32)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [232]:
mat= np.random.rand(10)
print(mat)
matsqrt=np.sqrt(mat)
print(matsqrt)
matsqrt[matsqrt<0.5]= 0
matsqrt

[0.59018223 0.29234572 0.1726746  0.67065392 0.49180963 0.40629719
 0.30329418 0.64781536 0.67974394 0.65552894]
[0.76823318 0.54069004 0.41554133 0.81893462 0.7012914  0.63741446
 0.55072151 0.80486978 0.82446585 0.80964741]


array([0.76823318, 0.54069004, 0.        , 0.81893462, 0.7012914 ,
       0.63741446, 0.55072151, 0.80486978, 0.82446585, 0.80964741])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [247]:
a=np.random.randint(0,12, size=10)
b=np.random.randint(0,12, size=10)
print(a)
print(b)
c= a[a>b]
d= b[b>a]
print(c)
print(d)
e= np.concatenate((c,d))
e

[ 5  9  0 10  5  3  2  0 11  8]
[ 2 10  5  8  7  6  8 10  5 11]
[ 5 10 11]
[10  5  7  6  8 10 11]


array([ 5, 10, 11, 10,  5,  7,  6,  8, 10, 11])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [248]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [250]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [256]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
new=np.delete(sampleArray, 0,1)
print(new)
np.insert(new,1,10,axis=1 )

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[43 73]
 [22 12]
 [94 66]]


array([[43, 10, 73],
       [22, 10, 12],
       [94, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [260]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
print(x)
print(y)
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [266]:
arr_20 = np.random.randint(10, size=(5,4))
print(arr_20)
np.sum(arr_20)

[[9 7 7 1]
 [5 0 0 4]
 [1 8 0 8]
 [8 2 9 7]
 [4 1 6 6]]


93